import Copyright from "@/components/copyright";
import Navigation from "@/components/navigation";
import theme from "@/theme";
import { Container } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute="class" />
        <ThemeProvider theme={theme}>
          <CssBaseline enableColorScheme />
          <Navigation />
          <Container sx={{ marginY: 4 }} maxWidth="lg">
            {children}
          </Container>
          <Copyright />
        </ThemeProvider>
      </body>
    </html>
  );
}
